name: 'Create OTA Release'
description: 'Creates OTA update releases'
author: 'Ning Shang (Thistle Technologies)'
inputs:
  release_name:
    description: 'Display name of the release. If not provided or empty, the unique manifest ID will be used'
    required: false
  release_type:
    description: 'Release type ("file", "zip_archive", or "rootfs")'
    required: true
    default: 'file'
  persist_dir_on_device:
    description: 'Path to the directory where the device can persist data'
    required: true
    default: ''
  artifacts_dir:
    description: 'Path to the directory where OTA update artifacts are stored'
    required: false
    default: ''
  rootfs_img_path:
    description: 'Path to the rootfs image file. Required only if release_type is "rootfs"'
    required: false
    default: ''
  zip_archive_dir:
    description: 'Path to the directory whose content will be zipped before releasing. Required only if release_type is "zip_archive"'
    required: false
    default: ''
  base_install_path_on_device:
    description: 'Path to base directory on device file system where OTA update artifacts will be installed. Required if release_type is "file" or "zip_archive"'
    required: false
    default: ''
  project_access_token:
    description: 'Project access token can be obtained from the project settings page in Thistle Control Center'
    required: true
    default: ''
  signing_key_management:
    description: 'Indicates how the signing key is managed ("local" or "remote")'
    required: true
    default: 'local'
  signing_key:
    description: 'Minisign signing key in Thistle format. Required only if signing_key_management is "local"'
    required: false
    default: ''
  signing_key_password:
    description: 'Password for the signing key. Required only if signing_key_management is "local" and the signing key is password protected'
    required: false
    default: ''
  backend_url:
    description: 'URL of the backend server that runs the OTA update service. If not provided, the Thistle service will be used'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
